name: Update Labor Statistics Data

on:
  schedule:
    - cron: "0 2 1 * *"  # Runs on the 1st day of each month at 2:00 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas

    - name: Run BLS data fetch script
      run: python fetch_bls_data.py

    - name: Commit and push updates
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add labor_stats.csv
        git commit -m "Update labor statistics data [skip ci]" || echo "No changes to commit"
        git push
